#!/usr/bin/env bash

sudo pkill python
sleep 1
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
rm -rf "${SCRIPT_DIR}/database.lock"
sudo "${SCRIPT_DIR}/venv/bin/python" "${SCRIPT_DIR}/__main__.py"
